RecetasApp.Web/Controllers/MedidasController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RecetasApp.Web.Data;
using RecetasApp.Web.Data.Entities;
using System.Linq;
using System.Threading.Tasks;

namespace RecetasApp.Web.Controllers
{
    public class MedidasController : Controller
    {
        private readonly DataContext _context;

        public MedidasController(DataContext context)
        {
            _context = context;
        }

        // GET: Medidas
        public async Task<IActionResult> Index()
        {
            return View(await _context.Medidas.ToListAsync());
        }

        // GET: Medidas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var medida = await _context.Medidas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (medida == null)
            {
                return NotFound();
            }

            return View(medida);
        }

        // GET: Medidas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Medidas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Medid,Abreviacion")] Medida medida)
        {
            if (ModelState.IsValid)
            {
                _context.Add(medida);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(medida);
        }

        // GET: Medidas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var medida = await _context.Medidas.FindAsync(id);
            if (medida == null)
            {
                return NotFound();
            }
            return View(medida);
        }

        // POST: Medidas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Medid,Abreviacion")] Medida medida)
        {
            if (id != medida.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(medida);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MedidaExists(medida.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(medida);
        }

        // GET: Medidas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var medida = await _context.Medidas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (medida == null)
            {
                return NotFound();
            }

            return View(medida);
        }

        // POST: Medidas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var medida = await _context.Medidas.FindAsync(id);
            _context.Medidas.Remove(medida);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MedidaExists(int id)
        {
            return _context.Medidas.Any(e => e.Id == id);
        }
    }
}

RecetasApp.Web/Controllers/RecetasController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RecetasApp.Web.Data;
using RecetasApp.Web.Data.Entities;
using RecetasApp.Web.Helpers;
using RecetasApp.Web.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace RecetasApp.Web.Controllers
{
    public class RecetasController : Controller
    {
        private readonly DataContext _context;
        private readonly IUserHelper _userHelper;
        private readonly ICombosHelper _combosHelper;
        private readonly IRecetaRepository _recetaRepository;

        public RecetasController(DataContext context, IUserHelper userHelper, ICombosHelper combosHelper, IRecetaRepository recetaRepository)
        {
            _context = context;
            _userHelper = userHelper;
            _combosHelper = combosHelper;
            _recetaRepository = recetaRepository;

        }

        public IActionResult Index()
        {
            return View(_context.Recetas
                .Include(r => r.User)
                .Include(r => r.Region)
                );
        }
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var receta = await _context.Recetas
                .Include(r => r.User)
                .Include(r => r.Region)
                .Include(r => r.PasosRecetas)

                .Include(r => r.RecetaIngredientes)
                .ThenInclude(i => i.Ingredientes)

                .Include(r => r.RecetaIngredientes)
                .ThenInclude(i => i.Medidas)

                .Include(r => r.Comentarios)
                .Include(r => r.Observacions)
                .Include(r => r.CategoriaComidaRecetas)

                .ThenInclude(c => c.CategoriaComidas)
                .Include(r => r.Likes)

                .FirstOrDefaultAsync(m => m.Id == id);

            if (receta == null)
            {
                return NotFound();
            }

            return View(receta);
        }


        // GET: Recetas1/Create
        public IActionResult Create()
        {
            ViewData["RegionId"] = new SelectList(_context.Regions, "Id", "NomRegion");
            ViewData["RecetaId"] = new SelectList(_context.Recetas, "Id", "Descripcion");

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(RecetaViewModel view)
        {
            if (ModelState.IsValid)
            {
                var path = string.Empty;

                if (view.ImageFile != null && view.ImageFile.Length > 0)
                {
                    var guid = Guid.NewGuid().ToString();
                    var file = $"{guid}.jpg";


                    path = Path.Combine(
                        Directory.GetCurrentDirectory(),
                        "wwwroot\\images\\Recetas",
                        file);

                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        await view.ImageFile.CopyToAsync(stream);
                    }

                    path = $"~/images/Recetas/{file}";
                }

                var receta = this.ToReceta(view, path);


                receta.User = await this._userHelper.GetUserByEmailAsync(this.User.Identity.Name);
                await this._recetaRepository.CreateAsync(receta);
                return RedirectToAction(nameof(Index));

            }

            return View(view);
        }

        private Receta ToReceta(RecetaViewModel view, string path)
        {
            return new RecetaViewModel
            {
                Id = view.Id,
                ImagenUrl = path,              
                Comentarios = view.Comentarios,
                Descripcion = view.Descripcion,
                Dificultad = view.Dificultad,               
                Nombre = view.Nombre,               
                Raciones = view.Raciones,
                RegionId = view.RegionId,
                Temporada = view.Temporada,
                Tiempo = view.Tiempo,              
                User = view.User




            };

        }



        /*
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind( "Nombre, Descripcion, Tiempo,Raciones,ImagenUrl,Temporada," +
            "Dificultad,ActiComentarios,NumLikes,User,RegionId")]Receta receta)
        {
            


            try
            {
                if (ModelState.IsValid)
                {
                    _context.Recetas.Add(receta);
                    _context.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (DataException )
            {
                //Log the error (uncomment dex variable name and add a line here to write a log.
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
            }
            ViewData["RegionId"] = new SelectList(_context.Regions, "Id", "Id", receta.RegionId);
            return View(receta);
        }



        /*

        public ActionResult Create()
        {
            PopulateRegionsDropDownList();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "RecetaID,Nombre,Descripcion,Tiempo,Raciones,ImagenUrl," +
            "Temporada,Dificultad,ActiComentarios,NumLikes,Region")]Receta receta)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _context.Recetas.Add(receta);
                    _context.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (RetryLimitExceededException )
            {
                //Log the error (uncomment dex variable name and add a line here to write a log.)
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists," +
                    " see your system administrator.");
            }
            PopulateRegionsDropDownList(receta.Region);
            return View(receta);
        }
        
        
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Receta receta = _context.Courses.Find(id);
            if (receta == null)
            {
                return HttpNotFound();
            }
            PopulateRegionsDropDownList(receta.Region);
            return View(receta);
        }

        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public ActionResult EditPost(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var courseToUpdate = db.Courses.Find(id);
            if (TryUpdateModel(courseToUpdate, "",
               new string[] { "Title", "Credits", "DepartmentID" }))
            {
                try
                {
                    db.SaveChanges();

                    return RedirectToAction("Index");
                }
                catch (RetryLimitExceededException)
                {
                    //Log the error (uncomment dex variable name and add a line here to write a log.
                    ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator.");
                }
            }
            PopulateDepartmentsDropDownList(courseToUpdate.DepartmentID);
            return View(courseToUpdate);
        }




        */

        // POST: Recetas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nombre,Descripcion,Tiempo,Raciones,ImagenUrl,Temporada,Dificultad,ActiComentarios,NumLikes")] Receta receta)
        {
            if (id != receta.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(receta);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RecetaExists(receta.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(receta);
        }

        // GET: Recetas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var receta = await _context.Recetas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (receta == null)
            {
                return NotFound();
            }

            return View(receta);
        }

        // POST: Recetas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var receta = await _context.Recetas.FindAsync(id);
            _context.Recetas.Remove(receta);
            await _context.SaveChangesAsync();

RecetasApp.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RecetasApp.Web</title>

    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    
    <!-- Favicon -->
    <link rel="icon" href="~/img/core-img/favicon.ico">

    <!-- Core Stylesheet -->
    <link href="~/style.css" rel="stylesheet">

    <!-- Responsive CSS -->
    <link href="~/css/responsive/responsive.css" rel="stylesheet">

    
</head>
<body>
    <!-- Preloader Start
    <div id="preloader">
        <div class="yummy-load"></div>
    </div>-->
    
    <!-- ****** Top Header Area Start ****** -->
    <div class="top_header_area">
        <div class="container">
            <div class="row">
                <div class="col-5 col-sm-6">
                    <!--  Top Social bar start -->
                    <div class="top_social_bar">

                        <a href="https://github.com/NicolasDurante"><i class="fa fa-github-alt" aria-hidden="true" style="padding-right:40px"></i></a>

                        @if (this.User.IsInRole("Admin"))
                        {
                            <p style=" padding-left:80px;">
                                <a href="~/Account" class="btn btn-primary"
                                   style="background-color:blue;
                                        font-size:large;border-color:blue;
                                        border-radius: 15px; width:200px;
                                        height:40px; line-height:20px; ">
                                    <i class="glyphicon glyphicon-plus"></i>Administrador
                                </a>
                            </p>
                         }
                    </div>
                </div>
                <!--  Login Register Area -->
                <div class="col-7 col-sm-6">
                    <div class="signup-search-area d-flex align-items-center justify-content-end">
                        <div class="login_register_area d-flex">
                           
                            @if (!this.User.Identity.IsAuthenticated)
                            {
                                <div class="login">
                                    <a href="~/Account/Register">Registrarse</a>
                                </div>
                                <div class="register">
                                    <a href="~/Account/Login">Iniciar sesion</a>
                                </div>
                            }
                            @if (this.User.Identity.IsAuthenticated)
                            {
                                <div class=fa-user-alt>
                                    <a asp-area="" asp-controller="Account" asp-action="ChangeUser"> @this.User.Identity.Name</a>

                                </div>
                                <div class="">
                                    <a asp-area="" asp-controller="Account" asp-action="Logout"><b>(Cerrar sesión)</b></a>
                                </div>
                            }
                        </div>
                        <!-- Search Button Area
                        <div class="search_button">
                            <a class="searchBtn" href="#"><i class="fa fa-search" aria-hidden="true"></i></a>
                        </div>
                        <!-- Search Form
                        <div class="search-hidden-form">
                            <form action="#" method="get">
                                <input type="search" name="search" id="search-anything" placeholder="Search Anything...">
                                <input type="submit" value="" class="d-none">
                                <span class="searchBtn"><i class="fa fa-times" aria-hidden="true"></i></span>
                            </form>
                        </div>-->
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- ****** Top Header Area End ****** -->
    <!-- ****** Header Area Start ****** -->
    <header class="header_area">
        <div class="container">
            <div class="row">
                <!-- Logo Area Start -->
                <div class="col-12">
                    <div class="logo_area text-center">
                        <a href="~/" class="yummy-logo">RecetApp</a>
                    </div>
                </div>
            </div>

            
        </div>
    </header>

    @*
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">RecetApp</a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a asp-area="" asp-controller="Home" asp-action="Index">Inicio</a></li>

                        <li><a asp-area="" asp-controller="Recetas" asp-action="Index">Recetas</a></li>
                        <li><a asp-area="" asp-controller="CategoriaComidas" asp-action="Index">Categorias Comidas</a></li>
                        <li><a asp-area="" asp-controller="Ingredientes" asp-action="Index">Ingredientes</a></li>
                        <li><a asp-area="" asp-controller="Medidas" asp-action="Index">Medidas</a></li>
                        <li><a asp-area="" asp-controller="Regions" asp-action="Index">Regiones</a></li>
                        <li><a asp-area="" asp-controller="RecetasPrueba" asp-action="Index">RecetasPrueba</a></li>
                        <li><a asp-area="" asp-controller="PasosRecetas" asp-action="Index">PasosRecetas</a></li>

                        @if (this.User.IsInRole("Admin"))
                        {
                            <li><a asp-area="" asp-controller="Account" asp-action="Index">Usuarios</a></li>
                        }


                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        @if (this.User.Identity.IsAuthenticated)
                        {
                            <li><a asp-area="" asp-controller="Account" asp-action="ChangeUser">@this.User.Identity.Name</a></li>
                            <li><a asp-area="" asp-controller="Account" asp-action="Logout">Cerrar sesión</a></li>
                        }
                        else
                        {
                            <li><a asp-area="" asp-controller="Account" asp-action="Login">Acceder</a></li>
                        }
                    </ul>
                </div>
            </div>
        </nav>

        <partial name="_CookieConsentPartial" />
    *@
<div class="container body-content">
    @RenderBody()
    <hr />
    <!-- ****** Instagram Area Start ****** -->
    <div class="instargram_area owl-carousel section_padding_100_0 clearfix" id="portfolio">

        <!-- Instagram Item -->
        <div class="instagram_gallery_item">
            <!-- Instagram Thumb -->
            <img src="~/img/instagram-img/1.jpg" alt="">
            <!-- Hover -->

        </div>



        <!-- Instagram Item -->
        <div class="instagram_gallery_item">
            <!-- Instagram Thumb -->
            <img src="~/img/instagram-img/2.jpg" alt="">

        </div>

        <!-- Instagram Item -->
        <div class="instagram_gallery_item">
            <!-- Instagram Thumb -->
            <img src="~/img/instagram-img/3.jpg" alt="">

        </div>

        <!-- Instagram Item -->
        <div class="instagram_gallery_item">
            <!-- Instagram Thumb -->
            <img src="~/img/instagram-img/4.jpg" alt="">

        </div>

        <!-- Instagram Item -->
        <div class="instagram_gallery_item">
            <!-- Instagram Thumb -->
            <img src="~/img/instagram-img/5.jpg" alt="">

        </div>

        <!-- Instagram Item -->
        <div class="instagram_gallery_item">
            <!-- Instagram Thumb -->
            <img src="~/img/instagram-img/6.jpg" alt="">

        </div>

    </div>
    <!-- ****** Our Creative Portfolio Area End ****** -->
    <!-- ****** Footer Social Icon Area Start ****** -->
    <div class="social_icon_area clearfix">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="footer-social-area d-flex">

                        <div class="single-icon">
                            <a href="https://www.linkedin.com/in/nicolas-durante-95b785140/"><i class="fa fa-linkedin-square" aria-hidden="true"></i><span>linkedin</span></a>
                        </div>
                        <div class="single-icon">
                            <a href="https://github.com/NicolasDurante"><i class="fa fa-github" aria-hidden="true"></i><span>GitHub</span></a>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- ****** Footer Social Icon Area End ****** -->
    <!-- ****** Footer Menu Area Start ****** -->
    <footer class="footer_area">


        <div class="container">
            <div class="row">
                <div class="col-12">
                    <!-- Copywrite Text -->
                    <div class="copy_right_text text-center">
                        <p>RecetApp - Copyright 2019 Todos los derechos reservados </p>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- ****** Footer Menu Area End ****** -->
    <!-- Jquery-2.2.4 js -->
    <script src="~/js/jquery/jquery-2.2.4.min.js"></script>
    <!-- Popper js -->
    <script src="~/js/bootstrap/popper.min.js"></script>
    <!-- Bootstrap-4 js -->
    <script src="~/js/bootstrap/bootstrap.min.js"></script>
    <!-- All Plugins JS -->
    <script src="~/js/others/plugins.js"></script>
    <!-- Active JS -->
    <script src="~/js/active.js"></script>
</div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/node_modules/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/node_modules/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)

    
</body>
</htmllang="en">